export enum ORDER_TYPES {
  READY = 'READY',
  PREORDER = 'PREORDER',
  PRESCRIPTION = 'PRESCRIPTION',
}

export enum ORDER_STATUS {
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  ON_HOLD = 'ON_HOLD',
  PROCESSING = 'PROCESSING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum PRESCRIPTION_STATUS {
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_UPDATE = 'NEEDS_UPDATE',
  APPROVED = 'APPROVED',
  IN_MANUFACTURING = 'IN_MANUFACTURING',
  READY_TO_SHIP = 'READY_TO_SHIP',
  COMPLETED = 'COMPLETED',
}
