version: '3'
services:
  backend:
    image: lthung0412/wdp-be:latest
    pull_policy: always
    container_name: wdp-backend
    restart: unless-stopped
    ports:
      
    image: backend-image
    environment:
      - MONGODB_URI_LOCAL=
      - OTHER_ENV_VARIABLE=value
  frontend:
    image: frontend-image
    ports:
      - "80:80"
