version: '3'
services:
  backend:
    image: backend-image
    environment:
      - MONGODB_URI_LOCAL=
      - OTHER_ENV_VARIABLE=value
  frontend:
    image: frontend-image
    ports:
      - "80:80"