/**
 * Inventory Movement Type Enumeration
 */
export enum INVENTORY_MOVEMENT_TYPE {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  RETURN_IN = 'RETURN_IN',
  SCRAP = 'SCRAP',
  TRANSFER = 'TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  RESERVATION = 'RESERVATION',
  UNRESERVATION = 'UNRESERVATION',
}
